### ISSUE TITLE
[vue-function-api] CreateComponent is not working properly

### ISSUE THREAD

**Issue by Polaris-z** [vuejs/vue-function-api#13]
** How to use it correctly**

![image](https://user-images.githubusercontent.com/28984303/60315107-c96d3680-9997-11e9-9081-2ff74c78b7da.png)
![image](https://user-images.githubusercontent.com/28984303/60315120-d558f880-9997-11e9-935b-920a40e6c383.png)
![image](https://user-images.githubusercontent.com/28984303/60315195-2537bf80-9998-11e9-90fe-cc8cba1d244a.png)

**Comment by liximomo** [comment]
Sorry. Return function is not supported yet.

**Comment by Polaris-z** [comment]
> 抱歉。还不支持返回函数，现在不支持JSX。

额 是自己人就说中文了 ！
怎么在render 里使用 setup retrun 的值  
![image](https://user-images.githubusercontent.com/28984303/60320215-a187ce00-99ab-11e9-843b-a62325a3e10c.png)

![image](https://user-images.githubusercontent.com/28984303/60320203-97fe6600-99ab-11e9-9539-692ca9e54338.png)

**Comment by wjw99830** [comment]
@Polaris-z It's same as the 2.x render function. Use `this`.

**Comment by Polaris-z** [comment]
> @Polaris-z It's same as the 2.x render function. Use `this`.

The main reason is that if you cannot get the setup retrun value in the render, you have no way to use it

**Comment by wjw99830** [comment]
> The main reason is that if you cannot get the setup retrun value in the render, you have no way to use it
Well, on the other hand, function-api provides powerful capabilities to extract logic, not just a new render function.

**Comment by posva** [comment]
Closing in favor of https://github.com/vuejs/vue-function-api/issues/20
