### ISSUE TITLE
Typescript props type inference is incorrect

### ISSUE THREAD

**Issue by wcldyx** [vuejs/vue-function-api#15]
# The type of msg should be string, but is inferred to be of type StringConstructor
```javascript 
import { createComponent } from 'vue-function-api'

    const MyComponent = createComponent({
        props: {
            msg: String
        },
        setup(props) {
            console.log(props.msg == '1'); // string | undefined
           // Error:(13, 25) TS2367: This condition will always return 'false' since the types 'StringConstructor' and '"1"' have no overlap.
        }
    })
```

**Comment by jsmith** [comment]
The PR from @ChuChencheng works great!

There are still issues with the `required` option. Here is an example from the RFC:
```javascript
import { createComponent } from 'vue'

createComponent({
  props: {
    foo: {
      type: String,
      required: true
    },
    bar: {
      type: String
    }
  } as const,
  setup(props) {
    props.foo // "string" as expected
    props.bar // should be -> "string | undefined" but it actually "string"
  }
})
```

**Comment by beeplin** [comment]
@liximomo Do we have any plan to merge #16 and fix the `required` issue mentioned above by @jsmith ?

**Comment by IlCallo** [comment]
Trying it out as well, found some problems with props inference too.

```ts
props: {
    // complexObject: {
    //   type: (Object as unknown) as PropType<ComplexObject>,
    //   required: true,
    // }, <= inferred as  {type: ComplexObject, required true}, should be inferred as ComplexObject
    complexObject: (Object as unknown) as PropType<ComplexObject>, // <= inferred as ComplexObject, but there is no required, should be inferred as optional
  } as const,
```

In general, [this section](https://github.com/vuejs/rfcs/blob/function-apis/active-rfcs/0000-function-api.md#required-props) doesn't seem to be enforced in the actual implementation.

PS: remember to import `PropType` from `vue-function-api`, it has a different signature from the one into `vue`

PS2:
> In 3.0, the props declaration is optional. If you don't want runtime props validation, you can omit props declaration and declare your expected prop types directly in TypeScript

If anyone is wondering, this isn't already working (as expected I guess)

**Comment by pauloevpr** [comment]
I have the same issue. Type inference does not work properly for props:

![image](https://user-images.githubusercontent.com/33222314/63078570-43c13c80-bf7f-11e9-9f2c-dea1c4b4cb3b.png)

My workaround to avoid Typescript compilation issues is to use `setup(props: any) {}` to skip inference.
