### ISSUE TITLE
Can export Context interface?

### ISSUE THREAD

**Issue by 404157386** [vuejs/vue-function-api#17]
Typescript need declare Context interface as param type when using setup method, can export it?

**Comment by liximomo** [comment]
I think the param type is optional.

![image](https://user-images.githubusercontent.com/9816225/60478233-80c5be00-9cb4-11e9-9731-a256f72a97a5.png)

**Comment by 404157386** [comment]
but i use deconstructor.like setup(props, {emit}). it hits error.




------------------ Original ------------------

**Comment by posva** [comment]
This is working correctly, if you still see the problem please open a new issue **with a boiled down repro**

**Comment by kukoo1** [comment]
@liximomo  It's working when used in createComponent method.
But it's not working when export as a sole object

`
export default {
setup(props, cxt) {
...
}
}
`

Typescript will complain that it imply `any` type on props and cxt.

**Comment by posva** [comment]
@liximomo I thought using `createComponent` was a requirement but it doesn't even appear in the readme. Is it necessary, optional for typings, or maybe something else?

**Comment by liximomo** [comment]
It is optional for both js and ts.

![image](https://user-images.githubusercontent.com/9816225/62301494-55004880-b4ab-11e9-93a1-46555feb9e48.png)

![image](https://user-images.githubusercontent.com/9816225/62301730-b1636800-b4ab-11e9-8959-f5bde01ca74c.png)

**Comment by bigmeow** [comment]
it not work unless I declare it as `any` type:
![image](https://user-images.githubusercontent.com/10484248/62820541-257ec980-bb98-11e9-98ab-a9c0a6ddbf75.png)


i try import type:
![image](https://user-images.githubusercontent.com/10484248/62820568-7f7f8f00-bb98-11e9-9964-540d3e00b2ba.png)

what should I do?
@posva
