### ISSUE TITLE
provide() can be called only once per component

### ISSUE THREAD

**Issue by boonyasukd** [vuejs/vue-function-api#24]
I've been testing out this new API, and found that `provide()` can be called only once per component. If there are more than one call to `provide()` (whether in `setup()` or hook functions), the latest `provide()` call seems to override all changes made by previous `provide()` calls. I believe this should be fixed.

To test this out, you can take a look at `App.vue` inside [my code sandbox](https://codesandbox.io/s/vue-3-complex-rfc-example-g7w1c). If you uncomment the second `provide()` line, the app will spit out injection error.

**Comment by liximomo** [comment]
The provide api is going to change. The current implementation has
digressed from the origin RFC.

Boonyasuk Dheeravongkit <notifications@github.com> 于 2019年7月5日周五 18:35写道：
