### ISSUE TITLE
the onErrorCaptured() hook is not working as expected

### ISSUE THREAD

**Issue by HermitSun** [vuejs/vue-function-api#25]
I tried to use the the `onErrorCaptured` hook just as I used it in 2.x:  [code in CodeSandbox ](https://codesandbox.io/s/onerrorcaptured-g6smm), outputs are in console.

The result is not in line with my expectation. Actually, the error was not captured, and because I used`Vue.config.warnHandler`, I found that the error was treated as a warn, `onErrorCaptured` was not called. But if I used it as 2.x, using `errorCaptured` hook, it works properly. Did I get something wrong? Thanks.

And sorry for my poor English.

**Comment by liximomo** [comment]
In fact, We don't have the `onErrorCaptured` hook now.

**Comment by HermitSun** [comment]
OK. Thank you.
