### ISSUE TITLE
context.slots should hold functions

### ISSUE THREAD

**Issue by SeregPie** [vuejs/vue-function-api#26]
`context.slots` should hold functions like Vue 3.0 describes.

**Comment by LinusBorg** [comment]
This plugin can't implement all details of the RFC because some are simply not feasable in Vue 2. This is one of those.

**Comment by SeregPie** [comment]
But `scopingSlots` already provide this feature and it will replace the `slots` in 3.0.

**Comment by LinusBorg** [comment]
In Vue 2, normal slots and scoped slots are still separated, and normal slots do return vnodes, not functions.

That's just how it works in 2.0 and this plugin won't change that.

**Comment by posva** [comment]
I think it will make sense to merge scopedSlots and slots in the `slots` property to make it possible to migrate from this lib to Vue 3

**Comment by thecrypticace** [comment]
Also note that Vue 2.6 already exposes normal slots as functions under `$scopedSlots`. So, if this lib were to require Vue 2.6 then context.slots could be able to mirror `this.$scopedSlots`, no?

**Comment by liximomo** [comment]
@thecrypticace The `context.slots` will be a mirror of `$scopedSlots` in the next release.
