### ISSUE TITLE
Do you support TypeScript-only Props Typing?

### ISSUE THREAD

**Issue by mya-ake** [vuejs/vue-function-api#27]
This specification.
https://github.com/vuejs/rfcs/blob/function-apis/active-rfcs/0000-function-api.md#typescript-only-props-typing

This component's `props` will be an empty object.
```
<template>
  <div> <!-- There is a div to prevent inheritance -->
    <button :type="type" :disabled="disabled"><slot /></button>
  </div>
</template>

<script lang="ts">
import { createComponent } from 'vue-function-api';

type Props = {
  type?: 'button' | 'submit';
  disabled?: boolean;
};

export default createComponent({
  setup(props: Props) {
    console.log(props); // Empty object {}
    const { type = 'button', disabled = false } = props;
    return {
      type,
      disabled,
    };
  },
});
</script>
```

**Comment by liximomo** [comment]
Can you provide an online reproduction?

**Comment by mya-ake** [comment]
@liximomo 

reproduction
https://mya-ake.github.io/ts-function-api-props-reproduction/index.html

code
https://github.com/mya-ake/ts-function-api-props-reproduction

**Comment by liximomo** [comment]
You still need to provide the props option with the `createComponent` API.  The `createComponent` is only a basic implementation now.

```js
export default createComponent({
  props: ['type', 'disabled'] as any as PropType<Props>,
  setup(props) {
    console.log(props); // Empty object {}
    const { type = 'button', disabled = false } = props;
    return {
      type,
      disabled,
    };
  },
});
```

**Comment by mya-ake** [comment]
@liximomo 

I see, it is implemented like that.
Thank you for teaching me!
