### ISSUE TITLE
this.nextTick()

### ISSUE THREAD

**Issue by kwanjas3** [vuejs/vue-function-api#28]
I have been relying on this for a significant part of a QA application I have been writing. Will this be available in some form or another in Vue 3? or should I begin rewriting things in .then()?

Thanks

**Comment by u3u** [comment]
> Defer the callback to be executed after the next DOM update cycle. Use it immediately after you’ve changed some data to wait for the DOM update. This is the same as the global `Vue.nextTick`, except that the callback’s this context is automatically bound to the instance calling this method.

<https://vuejs.org/v2/api/#Vue-nextTick>

**Comment by thommath** [comment]
I am not sure if it will be available in the Vue 3 API, but now it is available through the context.root element in this API.

```
setup(_, { root }) {
  root.$nextTick(() => console.log('hi'));
}
```

**Comment by kwanjas3** [comment]
> I am not sure if it will be available in the Vue 3 API, but now it is available through the context.root element in this API.
> 
> ```
> setup(_, { root }) {
>   root.$nextTick(() => console.log('hi'));
> }
> ```

thanks, still better than my solution of importing Vue to call Vue.nextTick(()=>{})

**Comment by posva** [comment]
FYI, importing Vue to call `Vue.nextTick` is totally fine as a solution.
Not sure about how the usage of `nextTick` will be on v3 but it may be through a named import

Since `root` is part of the context and `$nextTick` is probably not going away, I would say using `root.$nextTick` is safe

**Comment by andrewspy** [comment]
Since `root` is deprecated in the setup() `context`, What's the correct way to invoke `nextTick()` inside setup?

**Comment by danielroe** [comment]
@andrewspy You can import it directly from `@vue/composition-api`.

**Comment by tusharkgeospoc** [comment]
Here you go - `import { nextTick } from '@nuxtjs/composition-api';`

**Comment by agm1984** [comment]
I did:

``` vue
import { nextTick } from 'vue'

...
await nextTick()
```
