### ISSUE TITLE
unit test with typescript guide

### ISSUE THREAD

**Issue by neuronetio** [vuejs/vue-function-api#31]
How to make unit test using jest / mocha with typescript?
`@vue/test-utils/shallowMount(component) => wrapper.vm.*` does not contain type definitions which are returned from component so I cannot access anything even if returned data from setup exists in the browser when logging component to console.
Could someone provide an example please?

For example how to test returned values from setup?
```js
export default {
  setup(){
    return { testThis: true };
  }
}
```

**Comment by neuronetio** [comment]
Ok, it was simple as `(wrapper.vm as any).testThis` :)P
Of course we need to `import {plugin} from 'vue-function-api';  Vue.use(plugin)` in our test case.

**Comment by IlCallo** [comment]
Look [here](https://github.com/vuejs/rfcs/blob/function-apis/active-rfcs/0000-function-api.md#type-inference-1), you probably need to wrap your component into a `createComponent` call
