### ISSUE TITLE
使用vuex只能一个个的computed吗

### ISSUE THREAD

**Issue by zhaopeng95** [vuejs/vue-function-api#34]
使用vuex只能一个个的computed吗，能不能像vue2中的mapState那样直接展开

**Comment by SilentDepth** [comment]
mapState 是 Vuex 提供的功能，所以 computed 也应当是 Vuex 负责调用，vue-function-api 管不了了。不过你可以自己写个 hook 半自动化地实现类似效果。

**Comment by posva** [comment]
Duplicate of #8
