### ISSUE TITLE
[vue-function-api] "setup" must return a "Object", get "Function"

### ISSUE THREAD

**Issue by bskimball** [vuejs/vue-function-api#5]
When using the plugin I get this error
[vue-function-api] "setup" must return a "Object", get "Function"

But the RFC says you can return a function from setup for manual renders https://github.com/vuejs/rfcs/blob/function-apis/active-rfcs/0000-function-api.md#usage-with-manual-render-functions

like this
```
import { value, createElement as h } from 'vue'

const MyComponent = {
  setup(initialProps) {
    const count = value(0)
    const increment = () => { count.value++ }

    return (props, slots, attrs, vnode) => (
      h('button', {
        onClick: increment
      }, count.value)
    )
  }
}
```

**Comment by liximomo** [comment]
The RFC is keeping changing. This is not supported now.

**Comment by bskimball** [comment]
Thanks. Do you want me to just close the issue and wait or do you want me to leave it open?

**Comment by liximomo** [comment]
The most important part of the RFC is logic composition. We may not and can't cover all piece of it.
