### ISSUE TITLE
How to access current vm in setup() function?

### ISSUE THREAD

**Issue by Bosee** [vuejs/vue-function-api#50]
if use context.root will get the root vm of entire page, can i access current vm in setup function? i need to get the $route or $store of current vm instead of root vm.

**Comment by posva** [comment]
No, `this` is not accessible in `setup`. But you can access those properties in the root vm, it's they same reference in all Component instances. Why would it be different in your case?

**Comment by kidonng** [comment]
https://github.com/vuejs/vue-function-api/issues/39#issuecomment-516821618
