### ISSUE TITLE
Missing Typescript examples?

### ISSUE THREAD

**Issue by pauloevpr** [vuejs/vue-function-api#51]
Type Inference was a major motivation behind the Function-API. Surprisingly, I can't seem to find examples or even mentions to Typescript support in the [README.md](https://github.com/vuejs/vue-function-api/blob/master/README.md). Only the [Function-API RFC](https://github.com/vuejs/rfcs/blob/function-apis/active-rfcs/0000-function-api.md#type-inference-1) seems to cover Typescript support.

**Comment by posva** [comment]
It works out of the box, pretty much everything is automatically or explicitly inferred because of how the api is designed. What were you expecting exactly?

**Comment by pauloevpr** [comment]
I was expecting to see Typescript-specific examples, such as the ones in the RFC using createComponent() and showing how type inference works with props.

Everyone who's been following the RFCs pretty much knows that the Function-API supports Typescript naturally. But it would be great to make things more explicit especially for developers getting started with the new API.

I really want this epic API to take off.

**Comment by posva** [comment]
Yeah, I think having docs in js makes it easy for both javascript and typescript developers to pick it up. Did you find any blocker when using typescript? Something that didn't work out of the box?

**Comment by pauloevpr** [comment]
Typescript only works properly for me when using `createComponent`. 

![image](https://user-images.githubusercontent.com/33222314/62687439-208c0f80-ba0a-11e9-824a-3d9a1642c812.png)

![image](https://user-images.githubusercontent.com/33222314/62687314-e1f65500-ba09-11e9-8a14-7ba50ee9bae2.png)

**Comment by theWorkFsz** [comment]
@pauloevpr  you can use `Vue.extend()`   to let TypeScript properly infer types  inside Vue component options

https://vuejs.org/v2/guide/typescript.html#Basic-Usage

**Comment by pauloevpr** [comment]
I am not sure if I got your point. We are discussing about the new Function-API. According to the RFC:

"createComponent is conceptually similar to 2.x's Vue.extend, but it is a no-op and only needed for typing purposes."

So `createComponent` must be used instead of `Vue.extend`. 

I opened this issue to report that the READ.me on this repo lacks Typescript examples. That is all.

**Comment by mccxiv** [comment]
@pauloevpr looks like the readme has a Typescript section now 

https://github.com/vuejs/vue-function-api#typescript

**Comment by pauloevpr** [comment]
Great. I am happy now. Thanks.
