### ISSUE TITLE
what dose setCurrentVM function doing

### ISSUE THREAD

**Issue by theWorkFsz** [vuejs/vue-function-api#52]
Hey gays, I am learning the source code. 
and i see the `setCurrentVM` uesd  in `setup.ts` like: 
```js
...
    let preVm = getCurrentVM();
    setCurrentVM(vm);
    try {
      binding = setup(props, ctx);
    } catch (err) {
      logError(err, vm, 'setup()');
    } finally {
      setCurrentVM(preVm);
    }
...
```
I not sure why here need to set the `vm` before call `setup` and reset the `vm` in finally section .

Can anyone help me to understand waht this is doing? 
thx.

**Comment by liximomo** [comment]
Basically, it just stores the current vm into a global variable.
