### ISSUE TITLE
Type error with string key using provide/inject.

### ISSUE THREAD

**Issue by GodofHope** [vuejs/vue-function-api#56]
Here is the declaration file:
```
import { AnyObject } from '../types/basic';
import { Wrapper } from '../wrappers';
export interface Key<T> extends Symbol {
}
export declare function provide(data: AnyObject): void;
export declare function provide<T>(key: Key<T>, value: T | Wrapper<T>): void;
export declare function inject<T>(key: Key<T>): Wrapper<T> | void;
```

But the doc says:

### provide, inject

▸ provide(key: string | symbol, value: any)

▸ inject(key: string | symbol)

Equivalent with provide and inject from 2.x

So when I use string instead of exporting and importing symbols accross file, I got type error.

**Comment by liximomo** [comment]
It requires a force-cast via as `Key<T>` when using string as the key.

```js
import { Key, provide } from 'vue-function-api'

const key = '1' as any as Key<number>

provide(key, 1);
```
