### ISSUE TITLE
How to extends the context with e.g. $axios?

### ISSUE THREAD

**Issue by hipertracker** [vuejs/vue-function-api#60]
How to extend the context with own attrs? I use the Quasar framework with TypeScript and I can extends Vue instance with prototype inheritance. 
```import axios, { AxiosStatic } from 'axios';

export default async ({ Vue }) => {
  Vue.prototype.$axios = axios
}

declare module 'vue/types/vue' {
  interface Vue {
    $axios: AxiosStatic;
  }
}
```

Unfortunately,  `context.root` contains `Vue` instance but it does not contain any prototyped extensions. :(

**Comment by liximomo** [comment]
Are you sure you have extended the `Vue.prototype`?

**Comment by IlCallo** [comment]
Collateral question: is `context.root` the element root or, [as per previous API](https://vuejs.org/v2/api/#vm-root), the component tree root?

Until now we "littered" Vue prototype to easily access some globals ($axios, $vuex, etc), but this feels wrong with new function API, not being able to get `$el` from context and not being able to add those shortcuts to the context object itself.

Does it mean we should abandon Vue augmentation and only use VueConstructor augmentation, with stuff like `Vue.axios.get()` and similar?

**Comment by liximomo** [comment]
It should work if you properly extends the `Vue.prototype`.

**Comment by hipertracker** [comment]
The current Vue context is not available in setup(), it's available in onMounted().

```javascript
import axios, { AxiosInstance } from 'axios'

export default async ({ Vue }) => {
  Vue.prototype.$axios = axios
}

declare module 'vue/types/vue' {
  interface Vue {
    $axios: AxiosInstance;
  }
  interface VueConstructor {
    $axios: AxiosInstance;
  }
}
```

Component:

```javascript
import {  onMounted, createComponent } from 'vue-function-api'

export default createComponent({
  setup (props, context) {
    let axios
    //...
    onMounted(function (this: Vue) {
      axios = this.$axios
    })
  }
})
```

Alternative:

```typescript
import axios from 'axios';
import VueAxios from 'vue-axios';
import { VueConstructor } from 'vue';

export default async ({ Vue }: { Vue: VueConstructor }) => {
  Vue.use(VueAxios, axios);
};

declare module '*.vue' {
  export default Vue
}
```

```typescript
import {  onMounted, createComponent } from 'vue-function-api'

export default createComponent({
  setup (props, context) {
    let axios
    //...
    onMounted(function (this: Vue) {
      axios = this.axios
    })
  }
})
```

**Comment by liximomo** [comment]
```js
import Vue from 'vue';
import axios  from 'axios'

Vue.prototype.$axios = axios

export default createComponent({
  setup (props, context) {
     let axios = context.root.$axios;
     // ...
  }
})
```
