### ISSUE TITLE
"x" get called outside of "setup()" error if you have different versions of `vue-function-api`

### ISSUE THREAD

**Issue by FeliciousX** [vuejs/vue-function-api#61]
I am using a library **X** that uses `vue-function-api@2.1.1` and my own app uses `vue-function-api@2.1.2`

this creates 2 separate `vue-function-api`.

one in `node_modules/vue-function-api` (v2.1.2) 
and another one in `node_modules/X/node_modules/vue-function-api` (v2.1.1)

I noticed `vue-function-api` uses a [variable that is scoped within the package](https://github.com/vuejs/vue-function-api/blob/master/src/runtimeContext.ts#L5), when library X uses `inject` or `provide`, and you use it in your app, it will error out.

e.g.

```typescript
// library X using vue-function-api@2.1.1
export function useX() {
  const provider = inject<XProvider>(X_PROVIDER_KEY);
  if (!provider) {
    throw new Error('Unable to find provider');
  }
  return provider.value;
}

// app that uses vue-function-api@2.1.2
export default Vue.extend({
  setup(props, context) {
    useX() // error, inject is called outside of setup
  }
});
```

**Comment by liximomo** [comment]
A library should only use `vue-function-api` as a peer dependency.
