### ISSUE TITLE
Unable to use JSX directly in `setup()`

### ISSUE THREAD

**Issue by u3u** [vuejs/vue-function-api#64]
The `createElement` function has been added to the v2.2.0 release, which is great! 🎉

But the [`babel-sugar-inject-h`](https://github.com/vuejs/jsx/tree/dev/packages/babel-sugar-inject-h) plugin attempts to automatically inject `h` from `this.$createElement`, but there is no `this` in `setup()`, so JSX cannot be used directly.

**Comment by posva** [comment]
Could you open an issue there instead please?

**Comment by u3u** [comment]
In order to be compatible with the old code, I may have to use this plugin. 😅

https://github.com/vuejs/vue-function-api/blob/a7413ec53021887c90f777c29a88e5c04cff8329/src/install.ts#L45-L52

Can we import `createElement` here and build a `{ $createElement: createElement }` object to bind it to `this`? This may cause `this` in `setup()` to be not the expected `undefined`, but it will save a lot of trouble.

Now only need:

```js
import { createComponent } from 'vue-function-api';

// No longer need to manually import `createElement as h`
// import { createComponent, createElement as h } from 'vue-function-api';

export default createComponent({
  setup(initialProps) {
    // babel plugin will auto-inject h
    // const h = this.$createElement;
    return (props) => <div>{props.msg}</div>;
  },
});
```

Is there any good solution?
Please reopen this issue. 🙏

**Comment by posva** [comment]
I would say that the fix is skipping the plugin at https://github.com/vuejs/jsx/blob/dev/packages/babel-sugar-inject-h/src/index.js#L60-L62 if we are in a `setup` function but I'm not sure. You could give it a try and directly create a PR to the plugin 🙂 

We cannot add that hack as the lib must stay in sync with the RFC.

**Comment by PatrykWalach** [comment]
`h` won't be inserted if you use an arrow function, so you can do 
`jsx

import {
  createComponent,
  createElement
} from 'vue-function-api'

export default createComponent({
  setup: props => {
    const h = createElement

    return () => {
      return (
        <div>card</div>
      )
    }
  }
`

**Comment by u3u** [comment]
Hum... I also considered this, but this plugin should eventually solve this problem.

If the plugin imports `createElement` from `vue-function-api` to auto-inject `h` is it appropriate? Will the `createElement` function be exposed directly in future Vue?

**Comment by u3u** [comment]
@PatrykWalach As long as JSX is used in the function, `h` will be injected automatically. When I manually define `const h = createElement` there will be duplicate 'h` identifier exceptions

**Comment by PatrykWalach** [comment]
You won't get any errors using method above.
[link](https://github.com/vuejs/babel-plugin-transform-vue-jsx#h-auto-injection)
And exposing createElement is part of [rfc#28](https://github.com/vuejs/rfcs/pull/28) which changes the arguments of render function

**Comment by u3u** [comment]
@PatrykWalach Thank you! I didn't see it clearly before. 😂
