### ISSUE TITLE
NO MORE BREAKING CHANGE , NO MORE HACKING

### ISSUE THREAD

**Issue by GodofHope** [vuejs/vue-function-api#69]
It has been 3 days after I commented in #62.
In my option, there should fewer breaking change. We should not start a breaking change as long as we can solve it, not open as much changes as we can. The name and components options , will probably inherited from vue 2, while now this package force us to hack it.

I really you should consider it carefully.

Today I spend one hour baking up all the components I moved to vue-function-api, and roll back to vue-property-decorator which is uesd to support ts in vue2. Unless the package fully supported vue2 style which has not specificed how to be changed, I will not move on to it any further. I have more than 100 components to mantain, and I couldn't afford hacking and rehacking again while you release new version.

**Comment by posva** [comment]
> It has been 3 days after I commented in #62.

While I understand your frustration, this doesn't give you the right to open an issue with this tone and drop all your frustration on the author of the lib.

A more appropriate way would have been to list specific breaking changes so anyone can work on fixing them. We will gladly accept a new issue with a more appropriate tone and listing the breaking changes that shouldn't have happened

**Comment by GodofHope** [comment]
I have methoned it in my issue:

```
The name and components options , will probably inherited from vue 2, while now this package force us to hack it.
```

while you don't see it.

**Comment by GodofHope** [comment]
That 's now where the problem is.

I do understand your work, while thoughn I was complaining about rewriting my files over and over again, but my point is stop making break changes which the RFC does not methoned. Just remain as the vue2 do, instead of changing into a new style or let us hack it. I have NO furstation, but dispointment. Among the people who are using this package , maybe some just wanna try vue3 style, but I think there are amount of people like me just want to be fimilar to vue3, and we are trying  to prepare to move on to vue3. Just as its doc says(or used to say)(I didn't find the words just then): Just change the `vue-function-api` into `vue`. And we can move to vue3.

**Comment by GodofHope** [comment]
But while you upgraded it and I wrote with ts along with it, I rewrote all my components 4 times in order to clear the error I triggered after update. I WAS talking about `vue2 compatable` when the RFC and You didnot specific how to write in vue3.

**Comment by GodofHope** [comment]
I do think that you CAN understand what changes is `non-RFX mentioned` and `non-vue2 compatable`.

**Comment by GodofHope** [comment]
If you want, I can start a new issue listing all the non-RFC mentioned and non-vue2 compatable changes, but I don't think that is nessary, and I also think that let the people who already swithed to roll back is not a good idea. So please just stop breaking any more now, if only it is nessary.

**Comment by liximomo** [comment]
Sorry for that. We should warn the unstable status of vue-function-api. I think some beta releases would be necessary. We do consider our users.

**Comment by pangao66** [comment]
同样遇到这个问题,升级之后用ts发现 createComponent里面 只能写setup,  组件的其他属性,name,componets之类的都会报ts类型错误,这跟vue3目前公布的rfcs是违背的

**Comment by beeplin** [comment]
@pangao66 my workaround is to add `// @ts-ignore` before `name`.
 
Or please wait for bugfixes before updating to the current unstable version.

**Comment by GodofHope** [comment]
Beta release will be fine. And I think the types file should be improved.

**Comment by donnysim** [comment]
But the v3 is only in rfc and this package is in early development, you using this package is already accepting that there will be breaking changes until it settles down. There's no reason to go ham just because you can't wait for it to become stable. While i would prefer it used <1 versioning until it's stable, it is what it is.

**Comment by GodofHope** [comment]
> But the v3 is only in rfc and this package is in early development, you using this package is already accepting that there will be breaking changes until it settles down. There's no reason to go ham just because you can't wait for it to become stable. While i would prefer it used <1 versioning until it's stable, it is what it is.

Yes, I understand that, but i think breaking changes though a secend bit version should be list on the release panel. I did not get any warning for caution updating it.
