### ISSUE TITLE
The `ref` attribute does not work when using `createElement`

### ISSUE THREAD

**Issue by luwanquan** [vuejs/vue-function-api#70]
see the [case](https://codesandbox.io/s/vue-template-fgii5)

**Comment by luwanquan** [comment]
After preliminary inspection, The problem is caused by the **`53rd`** line `setCurrentVM(preVm)` of **`setup.ts`** file. When running for the first time, **`preVm`** is **`null`** and will overwrite the real **`currentVm`**. 

This should be the root cause of the ref node not being able to register to the correct parent node **`$refs`** attribute?

```javascript
    // ./src/setup.ts
    let preVm = getCurrentVM();
    setCurrentVM(vm);
    try {
      binding = setup(props, ctx);
    } catch (err) {
      logError(err, vm, 'setup()');
    } finally {
      setCurrentVM(preVm);  <<<<<< this line
    }
```

By comment this line of code, can temporarily solve the current problem, but I wonder if it will bring other side effects?

**Comment by liximomo** [comment]
It got fixed in the dev branch through https://github.com/vuejs/vue-function-api/blob/703bf300308ff3a550b236cd3de461fcec9f2213/src/setup.ts#L107-L109
and https://github.com/vuejs/vue-function-api/blob/703bf300308ff3a550b236cd3de461fcec9f2213/src/setup.ts#L148-L150

**Comment by luwanquan** [comment]
THKS ~
